/*
  This file is generated by CMake, changes made to this file will be lost.
  If you wish to modify this file, edit "config.h.in" instead.
*/


#ifndef __VIVOX_CONFIG_H__
#define __VIVOX_CONFIG_H__

#define SUBVERSION_CHANGE 2341
#define SUBVERSION_DATE "2007-09-19 16:41:55 -0400 (Wed, 19 Sep 2007)"
#define SDK_VERSION "2.1.2990.2341"
#define SDK_BRANCH "/repos/v2-sdk/branches/releases/2990"

#define VERSION_MAJOR 2
#define VERSION_MINOR 1
#define VERSION_MICRO 2990
#define VERSION_BUILD 2341
#define BUILD_DATE "Wed Sep 19 16:59:09 2007"
#define BUILD_HOST "BUILDBOX"
#define BUILD_PERSON "build"
#define VIVOX_BUILD_TYPE "Developer"

#ifdef __BIG_ENDIAN__
#define WORDS_BIGENDIAN 1
#else

#endif

#endif // __VERSIONINFO_H__


